name: Deploy with SSH Key

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/myclouduser/MyCloudApp
            git fetch && git reset --hard origin/main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            sudo nginx -t && sudo systemctl restart nginx
